// ...your full schema as you posted...
export const reports = pgTable("reports", { /* ... */ });
export const uploads = reports; // keep this alias
// inspections, defects, scores...
export type Report = typeof reports.$inferSelect;
export type NewReport = typeof reports.$inferInsert;
